---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_c4c3311e72cb
          env:
            - name: TZ
              value: Asia/Seoul
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-url
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: db-password
            - name: JWT_SIGN
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-sign
            - name: ACCESS_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: access-expiration
            - name: REFRESH_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: refresh-expiration
            - name: COOKIE_EXPIRATION
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: cookie-expiration
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: client-id
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: client-secret
            - name: REDIRECT_URI
              valueFrom:
                secretKeyRef:
                  name: oauth-secret
                  key: redirect-uri
          resources:
            requests:
              memory: 1Gi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
