namespace: default
resources:
  - nginx.yaml
  - mysql.yaml
  - backend.yaml
  - rabbitmq.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/default.conf
#  - name: init-db
#    files:
#      - configs/init.sql