namespace: default
resources:
  - nginx.yaml
  - mariadb.yaml
  - backend.yaml
configMapGenerator:
  - name: nginx
    files:
      - configs/nginx.conf
#  - name: init-db
#    files:
#      - configs/init.sql